CLASS zcra_cx_rule_kind DEFINITION
  PUBLIC
  INHERITING FROM zcra_cx_root
  CREATE PUBLIC.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcra_cx_rule_kind IMPLEMENTATION.
ENDCLASS.
